linters:
  enable:
    - revive
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goerr113
        - noctx
  max-per-linter: 0
  max-same: 0
